name: Run Job Bot

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 8 * * *' # يشتغل تلقائياً كل يوم الساعة 8 صباحاً

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install selenium webdriver-manager

      - name: Run Bot
        run: python apply.py

      - name: Commit changes
        run: |
          git config --global user.name 'Bot'
          git config --global user.email 'bot@example.com'
          git add all_emails.txt
          git commit -m "Update email list" || exit 0
          git push
