name: Auto Job Bot

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 8 * * *' # يشتغل تلقائياً كل يوم الساعة 8 صباحاً بتوقيت جرينتش

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Selenium and Driver
        run: |
          pip install selenium webdriver-manager

      - name: Run Bot Script
        run: python apply.py

      - name: Save Updated List
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add all_emails.txt
          git commit -m "Update emails: Removed sent items" || exit 0
          git push
